name: project-tvien

services:
  postgres:
    image: postgres:15-alpine
    container_name: tvien_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ProjectTviEnDb
    ports:
      - "5433:5432"
    volumes:
      - tvien_pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - tvien_net

  redis:
    image: redis:7-alpine
    container_name: tvien_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - tvien_net

  adminer:
    image: adminer
    container_name: tvien_adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - tvien_net

  prometheus:
    image: prom/prometheus
    container_name: tvien_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker-data/prometheus:/prometheus
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - tvien_net
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: tvien_grafana
    volumes:
      - ./docker-data/grafana:/var/lib/grafana
    ports:
      - "3005:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - tvien_net
    restart: unless-stopped

networks:
  tvien_net:
    driver: bridge

volumes:
  tvien_pgdata:

