--
-- PostgreSQL database dump
--

\restrict sW5lu4hQFhPuzEH3cntVyPyEanG5KgXvbdnsgvNAwzIhS8PVaiXMZ3fkbjB5xps

-- Dumped from database version 15.17
-- Dumped by pg_dump version 15.17

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Episodes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Episodes" (
    "EpisodeId" uuid NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "MovieId" integer NOT NULL,
    "SeasonNumber" integer NOT NULL,
    "EpisodeNumber" integer NOT NULL,
    "Title" character varying(255),
    "Description" text,
    "Duration" integer,
    "AirDate" date,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone
);


ALTER TABLE public."Episodes" OWNER TO postgres;

--
-- Name: Genres; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Genres" (
    "GenreId" integer NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Slug" character varying(100) NOT NULL
);


ALTER TABLE public."Genres" OWNER TO postgres;

--
-- Name: Genres_GenreId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Genres" ALTER COLUMN "GenreId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Genres_GenreId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: IngestJobs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."IngestJobs" (
    "JobId" character varying(50) NOT NULL,
    "MovieId" integer NOT NULL,
    "Status" character varying(50) NOT NULL,
    "Attempts" integer NOT NULL,
    "Priority" integer NOT NULL,
    "RawPath" character varying(1000),
    "Logs" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "StartedAt" timestamp with time zone,
    "FinishedAt" timestamp with time zone,
    "EpisodeId" uuid
);


ALTER TABLE public."IngestJobs" OWNER TO postgres;

--
-- Name: MediaAssets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MediaAssets" (
    "AssetId" character varying(50) NOT NULL,
    "MovieId" integer NOT NULL,
    "Type" character varying(50) NOT NULL,
    "Path" character varying(1000) NOT NULL,
    "Quality" character varying(50),
    "Checksum" character varying(255),
    "CreatedAt" timestamp with time zone NOT NULL,
    "RetentionPolicy" character varying(100),
    "EpisodeId" uuid
);


ALTER TABLE public."MediaAssets" OWNER TO postgres;

--
-- Name: MovieCrews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MovieCrews" (
    "Id" integer NOT NULL,
    "MovieId" integer NOT NULL,
    "PersonId" character varying(50) NOT NULL,
    "RoleId" integer NOT NULL,
    "CharacterName" character varying(255)
);


ALTER TABLE public."MovieCrews" OWNER TO postgres;

--
-- Name: MovieCrews_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."MovieCrews" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MovieCrews_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: MovieGenres; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MovieGenres" (
    "MovieId" integer NOT NULL,
    "GenreId" integer NOT NULL
);


ALTER TABLE public."MovieGenres" OWNER TO postgres;

--
-- Name: Movies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Movies" (
    "Id" integer NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "Title" character varying(255) NOT NULL,
    "OriginalTitle" character varying(255),
    "Slug" character varying(255) NOT NULL,
    "Description" text,
    "PosterUrl" character varying(1000),
    "BackdropUrl" character varying(1000),
    "TrailerUrl" character varying(1000),
    "ReleaseYear" integer,
    "Duration" integer,
    "AgeRating" character varying(10),
    "ViewCount" integer NOT NULL,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone
);


ALTER TABLE public."Movies" OWNER TO postgres;

--
-- Name: Movies_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Movies" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Movies_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Persons; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Persons" (
    "Id" character varying(50) NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "FullName" character varying(255) NOT NULL,
    "Slug" character varying(255),
    "Dob" date,
    "Gender" smallint,
    "Biography" text,
    "AvatarUrl" character varying(1000),
    "Nationality" character varying(50),
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Persons" OWNER TO postgres;

--
-- Name: Reviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Reviews" (
    "ReviewId" integer NOT NULL,
    "UserId" character varying(50) NOT NULL,
    "MovieId" integer NOT NULL,
    "Rating" integer NOT NULL,
    "Content" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Reviews" OWNER TO postgres;

--
-- Name: Reviews_ReviewId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Reviews" ALTER COLUMN "ReviewId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Reviews_ReviewId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: RoleInfos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."RoleInfos" (
    "Id" integer NOT NULL,
    "Name" character varying(100) NOT NULL
);


ALTER TABLE public."RoleInfos" OWNER TO postgres;

--
-- Name: RoleInfos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."RoleInfos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."RoleInfos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Roles" (
    "RoleId" integer NOT NULL,
    "Name" character varying(50) NOT NULL
);


ALTER TABLE public."Roles" OWNER TO postgres;

--
-- Name: Roles_RoleId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Roles" ALTER COLUMN "RoleId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Roles_RoleId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Streams; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Streams" (
    "MovieId" integer NOT NULL,
    "MasterPlaylist" character varying(1000),
    "CdnUrl" character varying(1000),
    "Status" character varying(50) NOT NULL,
    "ReadyAt" timestamp with time zone
);


ALTER TABLE public."Streams" OWNER TO postgres;

--
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "UserId" character varying(50) NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "GoogleId" character varying(255) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "DisplayName" character varying(255) NOT NULL,
    "AvatarUrl" character varying(1000),
    "RoleId" integer NOT NULL,
    "VipExpiresAt" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- Name: Videos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Videos" (
    "VideoId" uuid NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "MovieId" integer,
    "EpisodeId" uuid,
    "Resolution" character varying(50) NOT NULL,
    "MasterPlaylistUrl" character varying(1000),
    "SubtitleUrl" character varying(1000),
    "IsEncrypted" boolean NOT NULL,
    "EncryptionKey" character varying(255),
    "IV" character varying(255),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone
);


ALTER TABLE public."Videos" OWNER TO postgres;

--
-- Name: WatchHistories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."WatchHistories" (
    "HistoryId" integer NOT NULL,
    "UserId" character varying(50) NOT NULL,
    "MovieId" integer,
    "EpisodeId" uuid,
    "ProgressSeconds" integer NOT NULL,
    "IsCompleted" boolean NOT NULL,
    "WatchedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."WatchHistories" OWNER TO postgres;

--
-- Name: WatchHistories_HistoryId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."WatchHistories" ALTER COLUMN "HistoryId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."WatchHistories_HistoryId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Watchlists; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Watchlists" (
    "WatchlistId" integer NOT NULL,
    "UserId" character varying(50) NOT NULL,
    "MovieId" integer NOT NULL,
    "AddedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Watchlists" OWNER TO postgres;

--
-- Name: Watchlists_WatchlistId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Watchlists" ALTER COLUMN "WatchlistId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Watchlists_WatchlistId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Episodes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Episodes" ("EpisodeId", "IsDeleted", "MovieId", "SeasonNumber", "EpisodeNumber", "Title", "Description", "Duration", "AirDate", "Status", "CreatedAt", "UpdatedAt") FROM stdin;
\.


--
-- Data for Name: Genres; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Genres" ("GenreId", "IsDeleted", "Name", "Slug") FROM stdin;
2	f	Tình cảm	tinh-cam
3	f	Kinh dị	kinh-di
4	f	Hài kịch	hai-kich
5	f	Khoa học viễn tưởng	sci-fi
1	f	Hành động	hanh-dong
\.


--
-- Data for Name: IngestJobs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."IngestJobs" ("JobId", "MovieId", "Status", "Attempts", "Priority", "RawPath", "Logs", "CreatedAt", "StartedAt", "FinishedAt", "EpisodeId") FROM stdin;
6437da5040d544a4be89c7e1f4cd1d2e	2	pending	0	1	raw/2/71c043f28cc9434b9912ed37d46e2777_test-movie-01.mp4	\N	2026-05-01 00:36:29.214502+00	\N	\N	\N
f741717c30284532b5b3e030ead054a4	2	done	1	1	raw/2/ee09540ca70642f9a60d5d9bd4f20490_test-movie-2.mp4	Hoàn tất. Output: stream/movies/2/master.m3u8	2026-05-01 00:53:30.829672+00	2026-05-01 00:53:35.218723+00	2026-05-01 00:54:05.459589+00	\N
ed266b7884c14987970045ae7df6eb4f	1	done	1	1	raw/1/9f4edd45429d497496223b250ae28894_test-movie-4.mp4	Hoàn tất. Output: stream/1/master.m3u8	2026-05-01 03:11:26.183669+00	2026-05-01 03:11:28.806163+00	2026-05-01 03:12:02.96391+00	\N
eda0d111473b4f96ad9d94682a7345b8	6	done	1	1	raw/6/a263cb587a2642e4aaf114967b608f23_test-movie-7.mp4	Hoàn tất. Output: stream/6/master.m3u8	2026-05-01 08:58:33.730705+00	2026-05-01 08:58:37.163861+00	2026-05-01 08:59:04.57044+00	\N
2703db8b12df4c6b82e6b1e3b765b850	8	done	1	1	raw/8/1b505808c3394f8fbc54f5bf76ff9299_test-movie-7.mp4	Hoàn tất. Output: stream/8/master.m3u8	2026-05-01 09:16:07.371513+00	2026-05-01 09:16:07.527047+00	2026-05-01 09:16:36.559488+00	\N
455cf443ca764821b4bb369f8c9af906	10	done	1	1	raw/10/7d05adb48da742e08653523c03617a06_test-movie-7.mp4	Hoàn tất. Output: stream/10/master.m3u8	2026-05-07 17:27:05.142768+00	2026-05-07 17:27:08.950786+00	2026-05-07 17:27:29.614978+00	\N
a0ef461bbbee408f9447960b07b1432a	12	processing	1	1	raw/12/1d12932561cd41b6b444c4f7a5063406_test-movie-5.mp4	\N	2026-05-07 17:48:21.325944+00	2026-05-07 17:48:23.98572+00	\N	\N
50f0d0f6250f436caebf4e714d133b49	12	done	1	1	raw/12/83301b1b109844e6a0e821b568ecb995_test-movie-4.mp4	Hoàn tất. Output: stream/12/master.m3u8	2026-05-07 18:00:44.850572+00	2026-05-07 18:00:47.950054+00	2026-05-07 18:02:33.021152+00	\N
af7666764d9f47ae9d893261d3ae7ecc	13	done	1	1	raw/13/fcc7fc9f341a4cf292acede801f311ff_test-movie-5.mp4	Hoàn tất. Output: stream/13/master.m3u8	2026-05-07 18:16:52.09954+00	2026-05-07 18:16:54.155847+00	2026-05-07 18:17:10.200861+00	\N
bef99bcef5f444a7adf72b99841a0be1	15	done	1	1	raw/15/665d5312f29949f4a3ef920092dcbf90_test-movie-5.mp4	Hoàn tất. Output: stream/15/master.m3u8	2026-05-08 08:27:18.359331+00	2026-05-08 08:27:22.2186+00	2026-05-08 08:27:40.761335+00	\N
\.


--
-- Data for Name: MediaAssets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."MediaAssets" ("AssetId", "MovieId", "Type", "Path", "Quality", "Checksum", "CreatedAt", "RetentionPolicy", "EpisodeId") FROM stdin;
720f0be3c3a145db8658e7c6de6ed7e1	2	MainVideo	raw/2/71c043f28cc9434b9912ed37d46e2777_test-movie-01.mp4	\N	\N	2026-05-01 00:36:29.142903+00	\N	\N
e9d63c0d090d423b98241daae3d735bf	2	MainVideo	raw/2/ee09540ca70642f9a60d5d9bd4f20490_test-movie-2.mp4	\N	\N	2026-05-01 00:53:30.768185+00	\N	\N
aa6eb09fabbc4835ad1982b56784a67c	1	MainVideo	raw/1/9f4edd45429d497496223b250ae28894_test-movie-4.mp4	\N	\N	2026-05-01 03:11:26.156421+00	\N	\N
54f131888cba43cdadf46c1878702aee	6	MainVideo	raw/6/a263cb587a2642e4aaf114967b608f23_test-movie-7.mp4	\N	\N	2026-05-01 08:58:33.712326+00	\N	\N
bfd1e01cd8f34ef99d99eefe3266da4f	8	MainVideo	raw/8/1b505808c3394f8fbc54f5bf76ff9299_test-movie-7.mp4	\N	\N	2026-05-01 09:16:07.370828+00	\N	\N
48ab48cd0d8c49f7abe8ffee2fa2a2f4	10	MainVideo	raw/10/7d05adb48da742e08653523c03617a06_test-movie-7.mp4	\N	\N	2026-05-07 17:27:05.126898+00	\N	\N
ff5b6a8a56bc45fcbb7c33c176e3415d	12	MainVideo	raw/12/1d12932561cd41b6b444c4f7a5063406_test-movie-5.mp4	\N	\N	2026-05-07 17:48:21.302271+00	\N	\N
e01c4e75abe44951acc6f0c71a41bb9b	12	MainVideo	raw/12/83301b1b109844e6a0e821b568ecb995_test-movie-4.mp4	\N	\N	2026-05-07 18:00:44.85016+00	\N	\N
d26142539ae74cf7b4e411d775d0e8ce	13	MainVideo	raw/13/fcc7fc9f341a4cf292acede801f311ff_test-movie-5.mp4	\N	\N	2026-05-07 18:16:52.076531+00	\N	\N
be0e3e636b12426692baa85b5f82872d	15	MainVideo	raw/15/665d5312f29949f4a3ef920092dcbf90_test-movie-5.mp4	\N	\N	2026-05-08 08:27:18.33628+00	\N	\N
\.


--
-- Data for Name: MovieCrews; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."MovieCrews" ("Id", "MovieId", "PersonId", "RoleId", "CharacterName") FROM stdin;
4	4	p5	2	Hero
5	5	p4	2	Supporting
8	2	p2	1	\N
9	2	p3	2	\N
13	6	p4	2	\N
14	6	p2	1	\N
15	8	p2	1	\N
16	10	p2	1	\N
18	13	p3	2	\N
19	15	p4	2	\N
20	12	p4	2	\N
\.


--
-- Data for Name: MovieGenres; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."MovieGenres" ("MovieId", "GenreId") FROM stdin;
2	5
3	1
4	5
5	4
1	1
1	5
6	2
8	1
8	5
10	4
12	3
13	2
13	4
15	3
15	5
\.


--
-- Data for Name: Movies; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Movies" ("Id", "IsDeleted", "Title", "OriginalTitle", "Slug", "Description", "PosterUrl", "BackdropUrl", "TrailerUrl", "ReleaseYear", "Duration", "AgeRating", "ViewCount", "Status", "CreatedAt", "UpdatedAt") FROM stdin;
3	t	Inception	\N	inception	Kẻ trộm giấc mơ	\N	\N	\N	2010	\N	\N	0	1	2026-04-30 06:44:47.71638+00	\N
4	t	Iron Man	\N	iron-man	Người sắt	\N	\N	\N	2008	\N	\N	0	1	2026-04-30 06:44:47.716386+00	\N
5	t	Gặp Lại Chị Bầu	\N	gap-lai-chi-bau	Phim Tết 2024	\N	\N	\N	2024	\N	\N	0	1	2026-04-30 06:44:47.716387+00	\N
6	f	Portrait lady on fire		portrait-lady-on-fire	Họa sĩ và người được vẽ chân dung	posters/poster_6_639132232075053293.webp	backdrops/backdrop_6_639132232086754502.webp	\N	2019	180	C18	0	0	2026-05-01 08:57:16.944233+00	2026-05-01 09:06:47.489447+00
2	f	Oppenheimer	\N	oppenheimer	Bom tấn của Nolan	posters/poster_2_639131999741462491.webp	backdrops/backdrop_2_639131962461875037.webp	\N	2023	\N	\N	0	1	2026-04-30 06:44:47.71638+00	2026-05-01 02:45:08.082538+00
8	f	test-01		test-01	test add	posters/poster_8_639132236051257222.webp	backdrops/backdrop_8_639132236069315783.webp	\N	2024	0	P	0	0	2026-05-01 09:13:25.108147+00	\N
1	f	blade runners 2049	\N	blade-runners-2049	Phim theo chân K (Ryan Gosling) — một người nhân tạo (replicant) thế hệ mới, làm nghề "Blade Runner" cho sở cảnh sát Los Angeles với nhiệm vụ săn lùng và tiêu diệt các replicant đời cũ bị lỗi.\n\nTrong một lần làm nhiệm vụ, K tình cờ khai quật được một bí mật chấn động: một replicant từng mang thai và sinh con. Việc người nhân tạo có khả năng sinh sản đe dọa trực tiếp đến trật tự xã hội và xóa nhòa ranh giới giữa "con người" và "công cụ". Hành trình điều tra sự thật đưa K đi tìm Rick Deckard (Harrison Ford) — một cựu Blade Runner đã mất tích 30 năm — đồng thời đẩy K vào một cuộc khủng hoảng hiện sinh sâu sắc về nguồn gốc, ký ức và việc liệu anh có thực sự mang một "linh hồn".	posters/poster_1_639132237059943910.webp	backdrops/backdrop_1_639132237070581860.webp	\N	2017	\N	13+	0	1	2026-04-30 06:44:47.716282+00	2026-05-01 09:15:05.980946+00
10	f	final test		final-test	final test	posters/poster_10_639137715514440669.webp	backdrops/backdrop_10_639137715527465751.webp	\N	2026	180	P	0	0	2026-05-07 17:25:51.184603+00	\N
13	f	final test lan cuoi		final-test-lan-cuoi	lần cuối	posters/poster_13_639137745685825468.webp	backdrops/backdrop_13_639137745698217712.webp	\N	2026	0	P	0	0	2026-05-07 18:16:08.210044+00	\N
15	f	testtesst	ssd	testtesst	dfgffdg	posters/poster_15_639138254378163961.webp	backdrops/backdrop_15_639138254391208522.webp	\N	2024	0	P	0	0	2026-05-08 08:23:57.378264+00	\N
12	f	final test lan 2		final-test-lan-2		posters/poster_12_639138313951735172.webp	backdrops/backdrop_12_639137728786269932.webp	\N	2027	1	P	0	0	2026-05-07 17:47:57.008168+00	2026-05-08 10:03:14.949331+00
\.


--
-- Data for Name: Persons; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Persons" ("Id", "IsDeleted", "FullName", "Slug", "Dob", "Gender", "Biography", "AvatarUrl", "Nationality", "CreatedAt") FROM stdin;
p1	f	Trấn Thành	tran-thanh	1987-02-05	\N	\N	\N	Việt Nam	2026-04-30 06:44:47.676683+00
p2	f	Christopher Nolan	christopher-nolan	1970-07-30	\N	\N	\N	Anh	2026-04-30 06:44:47.677162+00
p3	f	Cillian Murphy	cillian-murphy	1976-05-25	\N	\N	\N	Ireland	2026-04-30 06:44:47.677165+00
p4	f	Ninh Dương Lan Ngọc	lan-ngoc	1990-04-04	\N	\N	\N	Việt Nam	2026-04-30 06:44:47.677165+00
p5	f	Robert Downey Jr	rdj	1965-04-04	\N	\N	\N	Mỹ	2026-04-30 06:44:47.677166+00
2bbbeddd2b5d4bbfaba5059725cc698b	f	vnv	vnv	0323-12-21	1	con nhà người ta		vn	2026-05-07 17:58:56.11291+00
\.


--
-- Data for Name: Reviews; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Reviews" ("ReviewId", "UserId", "MovieId", "Rating", "Content", "CreatedAt", "UpdatedAt") FROM stdin;
\.


--
-- Data for Name: RoleInfos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."RoleInfos" ("Id", "Name") FROM stdin;
1	Đạo diễn
2	Diễn viên
3	Biên kịch
\.


--
-- Data for Name: Roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Roles" ("RoleId", "Name") FROM stdin;
1	Admin
2	VIP
3	Member
\.


--
-- Data for Name: Streams; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Streams" ("MovieId", "MasterPlaylist", "CdnUrl", "Status", "ReadyAt") FROM stdin;
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("UserId", "IsDeleted", "GoogleId", "Email", "DisplayName", "AvatarUrl", "RoleId", "VipExpiresAt", "IsActive", "CreatedAt") FROM stdin;
u1	f	g1	admin@tvien.com	Admin TviEn	\N	1	\N	t	2026-04-30 06:44:47.756444+00
u2	f	g2	vip1@gmail.com	Khách hàng VIP	\N	2	\N	t	2026-04-30 06:44:47.756521+00
u3	f	g3	member@gmail.com	Thành viên mới	\N	3	\N	t	2026-04-30 06:44:47.756522+00
u4	f	g4	user4@gmail.com	Trung Trần	\N	3	\N	t	2026-04-30 06:44:47.756523+00
u5	f	g5	test@gmail.com	Tester	\N	3	\N	t	2026-04-30 06:44:47.756523+00
\.


--
-- Data for Name: Videos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Videos" ("VideoId", "IsDeleted", "MovieId", "EpisodeId", "Resolution", "MasterPlaylistUrl", "SubtitleUrl", "IsEncrypted", "EncryptionKey", "IV", "CreatedAt", "UpdatedAt") FROM stdin;
2a0fc07b-2d8b-4e43-b091-0620019c6526	t	5	\N	1080p	https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8	\N	f	\N	\N	2026-04-30 06:44:47.871571+00	\N
3a9a2f86-7f97-414b-911d-c2f63122cfea	t	3	\N	1080p	https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8	\N	f	\N	\N	2026-04-30 06:44:47.871533+00	\N
3b1ab1ad-564e-40cb-ae3c-60530cfa2854	t	2	\N	1080p	https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8	\N	f	\N	\N	2026-04-30 06:44:47.871378+00	\N
67c17fac-339f-405f-9153-180d4588ac1c	t	4	\N	1080p	https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8	\N	f	\N	\N	2026-04-30 06:44:47.871555+00	\N
e801a695-17e0-4d32-a901-0c0911b5ef07	t	1	\N	1080p	https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8	\N	f	\N	\N	2026-04-30 06:44:47.84995+00	\N
129563b8-e016-46f3-96e7-58269d48f85e	f	2	\N	multi	stream/movies/2/master.m3u8	\N	t	q/i8LXhClUVXUj8ocPabtA==	\N	2026-05-01 00:54:05.435692+00	\N
c48a67dd-5b99-446f-aed5-c393ce586c84	f	1	\N	multi	stream/1/master.m3u8	\N	t	0ori9N/6ppg3hPbaGyPoNA==	\N	2026-05-01 03:12:02.941416+00	\N
7e955fee-41d2-4779-a55d-b1d4cc6a4ebd	f	6	\N	multi	stream/6/master.m3u8	\N	t	IJrMcc2JvQqFAczk+jB/cg==	\N	2026-05-01 08:59:04.545978+00	\N
67e9b395-a83a-48b5-b69b-7d8358c20dcf	f	8	\N	multi	stream/8/master.m3u8	\N	t	YPeTeoxORm6PtMmHVGIlMA==	\N	2026-05-01 09:16:36.559144+00	\N
849eead5-d493-4a8b-a867-5e59ef2cf9c1	f	10	\N	multi	stream/10/master.m3u8	\N	t	lZf4INSnfAgiPSy/oA4PtA==	\N	2026-05-07 17:27:29.586939+00	\N
abd368b5-c474-4cca-8a1a-063dfbbc084e	f	12	\N	multi	stream/12/master.m3u8	\N	t	04HPJmbhqoyIvc/GS/ke2A==	\N	2026-05-07 18:02:32.984574+00	\N
32ff909e-6dfd-4a35-804c-54ec15380cd7	f	13	\N	multi	stream/13/master.m3u8	\N	t	0hB4frRAim/b/xizlhLvfg==	\N	2026-05-07 18:17:10.171748+00	\N
f061bb78-a685-485f-9f4b-4faa83bef45e	f	15	\N	multi	stream/15/master.m3u8	\N	t	N4KgAR+QLI0qQ5Vy1jtLvg==	\N	2026-05-08 08:27:40.731575+00	\N
\.


--
-- Data for Name: WatchHistories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."WatchHistories" ("HistoryId", "UserId", "MovieId", "EpisodeId", "ProgressSeconds", "IsCompleted", "WatchedAt") FROM stdin;
\.


--
-- Data for Name: Watchlists; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Watchlists" ("WatchlistId", "UserId", "MovieId", "AddedAt") FROM stdin;
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260430064214_InitialRefactor	8.0.10
20260501002124_AddEpisodeIdToMediaAssets	8.0.10
\.


--
-- Name: Genres_GenreId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Genres_GenreId_seq"', 5, true);


--
-- Name: MovieCrews_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."MovieCrews_Id_seq"', 20, true);


--
-- Name: Movies_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Movies_Id_seq"', 16, true);


--
-- Name: Reviews_ReviewId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Reviews_ReviewId_seq"', 1, false);


--
-- Name: RoleInfos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."RoleInfos_Id_seq"', 4, false);


--
-- Name: Roles_RoleId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Roles_RoleId_seq"', 4, false);


--
-- Name: WatchHistories_HistoryId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."WatchHistories_HistoryId_seq"', 1, false);


--
-- Name: Watchlists_WatchlistId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Watchlists_WatchlistId_seq"', 1, false);


--
-- Name: Episodes PK_Episodes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Episodes"
    ADD CONSTRAINT "PK_Episodes" PRIMARY KEY ("EpisodeId");


--
-- Name: Genres PK_Genres; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Genres"
    ADD CONSTRAINT "PK_Genres" PRIMARY KEY ("GenreId");


--
-- Name: IngestJobs PK_IngestJobs; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."IngestJobs"
    ADD CONSTRAINT "PK_IngestJobs" PRIMARY KEY ("JobId");


--
-- Name: MediaAssets PK_MediaAssets; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MediaAssets"
    ADD CONSTRAINT "PK_MediaAssets" PRIMARY KEY ("AssetId");


--
-- Name: MovieCrews PK_MovieCrews; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MovieCrews"
    ADD CONSTRAINT "PK_MovieCrews" PRIMARY KEY ("Id");


--
-- Name: MovieGenres PK_MovieGenres; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MovieGenres"
    ADD CONSTRAINT "PK_MovieGenres" PRIMARY KEY ("MovieId", "GenreId");


--
-- Name: Movies PK_Movies; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Movies"
    ADD CONSTRAINT "PK_Movies" PRIMARY KEY ("Id");


--
-- Name: Persons PK_Persons; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Persons"
    ADD CONSTRAINT "PK_Persons" PRIMARY KEY ("Id");


--
-- Name: Reviews PK_Reviews; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Reviews"
    ADD CONSTRAINT "PK_Reviews" PRIMARY KEY ("ReviewId");


--
-- Name: RoleInfos PK_RoleInfos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."RoleInfos"
    ADD CONSTRAINT "PK_RoleInfos" PRIMARY KEY ("Id");


--
-- Name: Roles PK_Roles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Roles"
    ADD CONSTRAINT "PK_Roles" PRIMARY KEY ("RoleId");


--
-- Name: Streams PK_Streams; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Streams"
    ADD CONSTRAINT "PK_Streams" PRIMARY KEY ("MovieId");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("UserId");


--
-- Name: Videos PK_Videos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Videos"
    ADD CONSTRAINT "PK_Videos" PRIMARY KEY ("VideoId");


--
-- Name: WatchHistories PK_WatchHistories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WatchHistories"
    ADD CONSTRAINT "PK_WatchHistories" PRIMARY KEY ("HistoryId");


--
-- Name: Watchlists PK_Watchlists; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Watchlists"
    ADD CONSTRAINT "PK_Watchlists" PRIMARY KEY ("WatchlistId");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Episodes_MovieId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Episodes_MovieId" ON public."Episodes" USING btree ("MovieId");


--
-- Name: IX_Genres_Name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Genres_Name" ON public."Genres" USING btree ("Name");


--
-- Name: IX_Genres_Slug; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Genres_Slug" ON public."Genres" USING btree ("Slug");


--
-- Name: IX_IngestJobs_MovieId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_IngestJobs_MovieId" ON public."IngestJobs" USING btree ("MovieId");


--
-- Name: IX_MediaAssets_MovieId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MediaAssets_MovieId" ON public."MediaAssets" USING btree ("MovieId");


--
-- Name: IX_MovieCrews_MovieId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MovieCrews_MovieId" ON public."MovieCrews" USING btree ("MovieId");


--
-- Name: IX_MovieCrews_PersonId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MovieCrews_PersonId" ON public."MovieCrews" USING btree ("PersonId");


--
-- Name: IX_MovieCrews_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MovieCrews_RoleId" ON public."MovieCrews" USING btree ("RoleId");


--
-- Name: IX_MovieGenres_GenreId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MovieGenres_GenreId" ON public."MovieGenres" USING btree ("GenreId");


--
-- Name: IX_Movies_Slug; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Movies_Slug" ON public."Movies" USING btree ("Slug");


--
-- Name: IX_Persons_Slug; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Persons_Slug" ON public."Persons" USING btree ("Slug");


--
-- Name: IX_Reviews_MovieId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Reviews_MovieId" ON public."Reviews" USING btree ("MovieId");


--
-- Name: IX_Reviews_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Reviews_UserId" ON public."Reviews" USING btree ("UserId");


--
-- Name: IX_Users_Email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_Email" ON public."Users" USING btree ("Email");


--
-- Name: IX_Users_GoogleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_GoogleId" ON public."Users" USING btree ("GoogleId");


--
-- Name: IX_Users_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Users_RoleId" ON public."Users" USING btree ("RoleId");


--
-- Name: IX_Videos_EpisodeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Videos_EpisodeId" ON public."Videos" USING btree ("EpisodeId");


--
-- Name: IX_Videos_MovieId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Videos_MovieId" ON public."Videos" USING btree ("MovieId");


--
-- Name: IX_WatchHistories_EpisodeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_WatchHistories_EpisodeId" ON public."WatchHistories" USING btree ("EpisodeId");


--
-- Name: IX_WatchHistories_MovieId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_WatchHistories_MovieId" ON public."WatchHistories" USING btree ("MovieId");


--
-- Name: IX_WatchHistories_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_WatchHistories_UserId" ON public."WatchHistories" USING btree ("UserId");


--
-- Name: IX_Watchlists_MovieId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Watchlists_MovieId" ON public."Watchlists" USING btree ("MovieId");


--
-- Name: IX_Watchlists_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Watchlists_UserId" ON public."Watchlists" USING btree ("UserId");


--
-- Name: Episodes FK_Episodes_Movies_MovieId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Episodes"
    ADD CONSTRAINT "FK_Episodes_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES public."Movies"("Id") ON DELETE CASCADE;


--
-- Name: IngestJobs FK_IngestJobs_Movies_MovieId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."IngestJobs"
    ADD CONSTRAINT "FK_IngestJobs_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES public."Movies"("Id") ON DELETE CASCADE;


--
-- Name: MediaAssets FK_MediaAssets_Movies_MovieId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MediaAssets"
    ADD CONSTRAINT "FK_MediaAssets_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES public."Movies"("Id") ON DELETE CASCADE;


--
-- Name: MovieCrews FK_MovieCrews_Movies_MovieId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MovieCrews"
    ADD CONSTRAINT "FK_MovieCrews_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES public."Movies"("Id") ON DELETE CASCADE;


--
-- Name: MovieCrews FK_MovieCrews_Persons_PersonId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MovieCrews"
    ADD CONSTRAINT "FK_MovieCrews_Persons_PersonId" FOREIGN KEY ("PersonId") REFERENCES public."Persons"("Id") ON DELETE CASCADE;


--
-- Name: MovieCrews FK_MovieCrews_RoleInfos_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MovieCrews"
    ADD CONSTRAINT "FK_MovieCrews_RoleInfos_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."RoleInfos"("Id") ON DELETE CASCADE;


--
-- Name: MovieGenres FK_MovieGenres_Genres_GenreId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MovieGenres"
    ADD CONSTRAINT "FK_MovieGenres_Genres_GenreId" FOREIGN KEY ("GenreId") REFERENCES public."Genres"("GenreId") ON DELETE CASCADE;


--
-- Name: MovieGenres FK_MovieGenres_Movies_MovieId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MovieGenres"
    ADD CONSTRAINT "FK_MovieGenres_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES public."Movies"("Id") ON DELETE CASCADE;


--
-- Name: Reviews FK_Reviews_Movies_MovieId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Reviews"
    ADD CONSTRAINT "FK_Reviews_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES public."Movies"("Id") ON DELETE CASCADE;


--
-- Name: Reviews FK_Reviews_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Reviews"
    ADD CONSTRAINT "FK_Reviews_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("UserId") ON DELETE CASCADE;


--
-- Name: Streams FK_Streams_Movies_MovieId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Streams"
    ADD CONSTRAINT "FK_Streams_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES public."Movies"("Id") ON DELETE CASCADE;


--
-- Name: Users FK_Users_Roles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."Roles"("RoleId") ON DELETE CASCADE;


--
-- Name: Videos FK_Videos_Episodes_EpisodeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Videos"
    ADD CONSTRAINT "FK_Videos_Episodes_EpisodeId" FOREIGN KEY ("EpisodeId") REFERENCES public."Episodes"("EpisodeId");


--
-- Name: Videos FK_Videos_Movies_MovieId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Videos"
    ADD CONSTRAINT "FK_Videos_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES public."Movies"("Id");


--
-- Name: WatchHistories FK_WatchHistories_Episodes_EpisodeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WatchHistories"
    ADD CONSTRAINT "FK_WatchHistories_Episodes_EpisodeId" FOREIGN KEY ("EpisodeId") REFERENCES public."Episodes"("EpisodeId");


--
-- Name: WatchHistories FK_WatchHistories_Movies_MovieId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WatchHistories"
    ADD CONSTRAINT "FK_WatchHistories_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES public."Movies"("Id");


--
-- Name: WatchHistories FK_WatchHistories_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WatchHistories"
    ADD CONSTRAINT "FK_WatchHistories_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("UserId") ON DELETE CASCADE;


--
-- Name: Watchlists FK_Watchlists_Movies_MovieId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Watchlists"
    ADD CONSTRAINT "FK_Watchlists_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES public."Movies"("Id") ON DELETE CASCADE;


--
-- Name: Watchlists FK_Watchlists_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Watchlists"
    ADD CONSTRAINT "FK_Watchlists_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("UserId") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict sW5lu4hQFhPuzEH3cntVyPyEanG5KgXvbdnsgvNAwzIhS8PVaiXMZ3fkbjB5xps

