/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#e3e2e2",
        "on-primary-fixed": "#1a1c1c",
        "surface-tint": "#c6c6c6",
        "on-secondary-fixed": "#1b1c1c",
        "on-tertiary-fixed-variant": "#4b4643",
        "surface-container-low": "#1c1b1b",
        "on-secondary-container": "#b5b5b5",
        "error": "#ffb4ab",
        "on-secondary": "#303031",
        "inverse-on-surface": "#313030",
        "secondary-fixed-dim": "#c7c6c6",
        "surface-container-lowest": "#0e0e0e",
        "surface-container": "#201f1f",
        "on-tertiary": "#342f2d",
        "on-error-container": "#ffdad6",
        "on-background": "#e5e2e1",
        "on-primary-container": "#626363",
        "on-secondary-fixed-variant": "#464747",
        "outline": "#8e9192",
        "tertiary-fixed-dim": "#cdc5c1",
        "tertiary-fixed": "#eae1dd",
        "on-primary-fixed-variant": "#454747",
        "on-tertiary-fixed": "#1f1b19",
        "surface-container-high": "#2a2a2a",
        "on-primary": "#2f3131",
        "inverse-surface": "#e5e2e1",
        "background": "#141313",
        "surface-variant": "#353434",
        "primary-fixed-dim": "#c6c6c6",
        "secondary-container": "#464747",
        "secondary": "#c7c6c6",
        "primary": "#fdfdfc",
        "surface": "#141313",
        "error-container": "#93000a",
        "on-surface": "#e5e2e1",
        "primary-container": "#e0e0e0",
        "tertiary": "#fffbff",
        "surface-container-highest": "#353434",
        "inverse-primary": "#5d5f5f",
        "outline-variant": "#444748",
        "tertiary-container": "#e7deda",
        "primary-fixed": "#e2e2e2",
        "surface-dim": "#141313",
        "on-error": "#690005",
        "on-tertiary-container": "#67615e",
        "surface-bright": "#3a3939",
        "on-surface-variant": "#c4c7c8"
      },
      fontFamily: {
        sans: ['var(--font-inter)'],
        serif: ['var(--font-noto-serif)'],
      },
      fontSize: {
        "h1": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "h2": ["16px", { "lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-sm": ["13px", { "lineHeight": "18px", "letterSpacing": "0", "fontWeight": "400" }],
        "tabular-nums": ["13px", { "lineHeight": "18px", "letterSpacing": "0", "fontWeight": "500" }],
        "body-base": ["14px", { "lineHeight": "20px", "letterSpacing": "0", "fontWeight": "400" }],
        "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
};

export default config;
